version: '3.9'

services:
  occasia.api:
    image: ${DOCKER_REGISTRY-}occasiaapi
    build:
      context: .
      dockerfile: src/API/Occasia.Api/Dockerfile
    ports:
      - "6000:8080"
      - "6001:8081"
  
  occasia.database:
    image: postgres:latest
    container_name: Occasia.Database
    environment:
      - POSTGRES_DB=occasia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_occasia:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  occasia.seq:
    image: datalust/seq:latest
    container_name: Occasia.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"

volumes:
  postgres_occasia: